import { DataTypes } from "sequelize";

const Guardian = (db) => {
	return db.define("guardian", {
		id: {
			type: DataTypes.INTEGER,
			primaryKey: true,
			autoIncrement: true,
		},
		firstname: DataTypes.TEXT,
		lastname: DataTypes.TEXT,
		prefix: {
			type: DataTypes.ENUM,
			values: [
				"Mr.",
				"Mrs.",
				"Miss",
				"Ms.",
				"Dr.",
				"Prof.",
				"Rev.",
				"Sir",
				"Madam",
				"Mx.",
				"Hon.",
				"Lord",
				"Lady",
			],
			allowNull: true,
		},
		suffix: {
			type: DataTypes.ENUM,
			values: [
				"Jr.",
				"Sr.",
				"II",
				"III",
				"IV",
				"V",
				"PhD",
				"MD",
				"DDS",
				"Esq.",
				"CPA",
			],
			allowNull: true,
		},
		dateofbirth: DataTypes.DATE,

		ethnicity: {
			type: DataTypes.ENUM,
			values: ["Hispanic or Latino", "Not Hispanic or Latino"],
		},
		race: {
			type: DataTypes.ENUM,
			values: [
				"White",
				"Black or African American",
				"American Indian or Alaska Native",
				"Asian",
				"Native Hawaiian or Other Pacific Islander",
			],
		},
		address: DataTypes.TEXT,
		language: {
			type: DataTypes.ENUM,
			values: [
				"English",
				"Spanish",
				"Chinese (Mandarin, Cantonese)",
				"Tagalog",
				"Vietnamese",
				"French",
				"Arabic",
				"Korean",
				"Russian",
				"German",
				"Portuguese",
				"Japanese",
				"Hindi",
				"Urdu",
				"Persian (Farsi)",
				"Italian",
				"Polish",
				"Haitian Creole",
				"Hebrew",
				"Bengali",
				"Gujarati",
				"Greek",
				"Punjabi",
				"Thai",
				"Swahili",
				"Somali",
				"Burmese",
				"Amharic",
			],
		},
	});
};
